#!/usr/bin/env bash
# Regenerate DEPLOYMENTS.md from deployments/*.json (written by scripts/deploy.sh).
set -euo pipefail

cd "$(dirname "$0")/.."
command -v jq >/dev/null || { echo "jq not found" >&2; exit 1; }

{
  echo "# Deployments"
  echo
  echo "Generated by \`scripts/gen-deployments-md.sh\` from \`deployments/*.json\`. Do not edit by hand."
  echo
  echo "| Network | Contract ID | WASM hash | Admin | Git commit | Deployed (UTC) | stellar-cli |"
  echo "|---|---|---|---|---|---|---|"
  shopt -s nullglob
  for f in deployments/*.json; do
    jq -r '"| \(.network) | `\(.contract_id)` | `\(.wasm_hash)` | `\(.admin)` | `\(.git_commit[0:12])`\(if .git_dirty then " (dirty)" else "" end) | \(.deployed_at) | \(.stellar_cli) |"' "$f"
  done
} > DEPLOYMENTS.md
